// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarLab.Domain;

namespace SolarLab.Domain.Migrations
{
    [DbContext(typeof(AdsDbContext))]
    [Migration("20181002093951_reconnect_to_new_db")]
    partial class reconnect_to_new_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolarLab.Domain.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("SolarLab.Domain.AdvertComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdvertId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("AdvertComments");
                });

            modelBuilder.Entity("SolarLab.Domain.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("SolarLab.Domain.Advert", b =>
                {
                    b.HasOne("SolarLab.Domain.Board")
                        .WithMany("Adverts")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("SolarLab.Domain.AdvertComment", b =>
                {
                    b.HasOne("SolarLab.Domain.Advert")
                        .WithMany("AdvertComments")
                        .HasForeignKey("AdvertId");
                });
#pragma warning restore 612, 618
        }
    }
}
